# $HOME/.config/alacritty/alacritty.toml
# by Rito Ghosh 2023-10-06

# Alacritty now uses TOML formatting for its config files.
# This is a simple example.

# There are the specification here= https=//github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# It is not obvious how it translates to TOML. But it is extremely straightforward.

# example= WINDOW, COLORS, etc. are tables, and should be represented as [window], [colors], respectively.
# specifics of variables go under them. e.g.- look under "dynamic_padding" under-
# https=//github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#window
# write `dynamic_padding = true` (without backticks -`) under the table [window]
# for variables with multiple values, use "dotted keys". Like setting `padding.x = 5` under [window].
# This is simple. If not clear, do several trials and errors.

# Below is my initial set-up. The TOML homepage (https=//toml.io/en/v1.0.0) was very helpful in figuring this out. 
# I put the file alacritty.toml in $HOME/.config/alacritty. However it can be kept anywhere among the places mentioned in
# https=//github.com/alacritty/alacritty/tree/master#configuration

[window]

opacity = 0.8

padding.x = 10
padding.y = 5

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

# startup_mode = "Fullscreen"
dynamic_title = true

[font]

normal.family = "JetbrainsMono Nerd Font"
bold.family = "JetbrainsMono Nerd Font"
italic.family = "JetbrainsMono Nerd Font"
bold_italic.family = "JetbrainsMono Nerd Font"
# size = 11.50
size = 14
builtin_box_drawing = false 

offset = { x = 0, y = 0 }

[cursor]

style = { shape = "Beam", blinking = "Never" }
vi_mode_style = {shape = "Block",blinking= "Never"}

[keyboard]

bindings = [
{ key = "c", mods = "Control|Alt", action = "Copy" },
{ key = "v", mods = "Control|Alt", action = "Paste" },
]
# Tip= for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a 
# small box when a HEX is detected by the editor.

# tokyonight
# [colors]
#     [colors.primary]
#       # background= '#24283b'
#       background= '#0d0f18'
#       foreground= '#a9b1d6'
#
#     # Normal colors
#     [colors.normal]
#       black=   '#32344a'
#       red=     '#f7768e'
#       green=   '#9ece6a'
#       yellow=  '#e0af68'
#       blue=    '#7aa2f7'
#       magenta= '#ad8ee6'
#       cyan=    '#449dab'
#       white=   '#9699a8'
#
#     # Bright colors
#     [colors.bright]
#       black=   '#444b6a'
#       red=     '#ff7a93'
#       green=   '#b9f27c'
#       yellow=  '#ff9e64'
#       blue=    '#7da6ff'
#       magenta= '#bb9af7'
#       cyan=    '#0db9d7'
#       white=   '#acb0d0'

## catppuccin mocha
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

# [shell]
# program= "tmux"
