local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets("cpp", {
  s("cpp", {
    t({
      "#include <bits/stdc++.h>",
      "#include <ext/pb_ds/assoc_container.hpp>",
      "#include <ext/pb_ds/tree_policy.hpp>",
      "",
      "using namespace std;",
      "using namespace __gnu_pbds;",
      "",
      "#ifndef ONLINE_JUDGE",
      '#include "/home/aman/Templates/Debug/debug.hpp"',
      "#else",
      "#define debug(...)",
      "#define debugArr(...)",
      "#endif",
      "",
      "#define int long long",
      "#define all(x) (x).begin(), (x).end()",
      "#define eb emplace_back",
      "#define endl '\\n'",
      "#define inf 1e18",
      "#define f first",
      "#define s second",
      "typedef long double ld;",
      "typedef double dd;",
      "typedef tree<pair<int, int>, null_type, less<pair<int, int>>, rb_tree_tag,",
      "             tree_order_statistics_node_update>",
      "    pbds; // find_by_order, order_of_key",
      "",
      "#define input(a, n)                                                    \\",
      "  for (int i = 0; i < n; i++)                                          \\",
      "    cin >> a[i];",
      '#define yea(a) cout << (a ? "YES" : "NO") << endl;',
      "",
      "#define print(a)                                                       \\",
      "  for (auto it : a) {                                                  \\",
      "    cout << it << ' ';                                                 \\",
      "  };                                                                   \\",
      "  cout << endl;",
      "",
      "#define print2(a)                                                      \\",
      "  for (auto it : a) {                                                  \\",
      "    for (auto it2 : it) {                                              \\",
      "      cout << it2 << ' ';                                              \\",
      "    }                                                                  \\",
      "    cout << endl;                                                      \\",
      "  };                                                                   \\",
      "  cout << endl;",
      "",
      "void here_there_and_gone() {",
      "  ios::sync_with_stdio(false);",
      "  cin.tie(0);",
      "  cout.tie(0);",
      "}",
      "",
      "const int M = 1e9 + 7;",
      "",
      "void solve() {",
    }),
    i(1),
    t({
      "}",
      "",
      "int32_t main() {",
      "  here_there_and_gone();",
      "",
      "  int t;",
      "  cin >> t;",
      "  while (t--) {",
      "    solve();",
      "  }",
      "}",
    }),
  }),
})
